### ISSUE TITLE
Refine style of preso survey page

### ISSUE THREAD

**Issue by iAmWillShepherd** [OneSignalDevelopers/ngosi#26]
The current survey is looking OK, but it should be constrained to mobile sizes.

###### Responsive layout on desktop
<img width="1260" alt="Screen Shot 2021-12-15 at 5 24 48 PM" src="https://user-images.githubusercontent.com/1715082/146280370-84ca92d2-cd20-4f20-abdb-0dc00107ba1a.png">

###### Current mobile layout

<img width="730" alt="Screen Shot 2021-12-15 at 5 26 33 PM" src="https://user-images.githubusercontent.com/1715082/146280504-88e9a52b-9641-400d-ae98-50a40e51745d.png">

**Comment by Yohanan-Negash** [comment]
@iAmWillShepherd  I am going to go ahead and close this issue because ngosi has a different UI now and I don't seem to find the survey page. This is what the current survey page looks like : 
![Screen Shot 2022-06-22 at 11 02 04 AM](https://user-images.githubusercontent.com/89279465/175063608-f6f92a91-9c68-40e2-b74d-c9d46cc2c708.png)
